name: hackfinity
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  animated_text_kit: ^1.3.0
  modal_progress_hud: ^0.1.3
  google_maps_flutter: ^0.5.27+3
  search_map_place: ^0.3.0
  geolocator: ^3.0.1
  flutter_spinkit: ^3.1.0
  provider: ^4.0.4
  http: ^0.12.0+4
  flutter_rating_bar: ^3.0.1+1
  firebase_core: ^0.3.4
  firebase_auth: ^0.8.4+4
  cloud_firestore: ^0.9.13+1
  rflutter_alert: ^1.1.0
  dropdown_date_picker: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/d.png
    - images/cover.jpg
    - images/handwash.jpg
    - images/
    - images/sanitizer.jpg
    - images/d.png